server: http://192.168.178.6
downloadserver: https://releases.rancher.com
config:
  - cluster: location_X
    config_create: &location_X_create
      token: d506621a3d4acdf60d62475f1b2cb681
      os:
        hostname: harvester01
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII9lnqlqqlHszXPP8zHFlqrQ4utzVJMSTJI2Qba+zE1s sshkey-X
          - github:your_username
        password: 5up3rS3cr3t
        dns_nameservers:
          - 192.168.178.3
        ntp_servers:
          - ntp.data.centerx.org
          - ntp.data.centerx.org
      install:
        mode: create
        networks:
          harvester-mgmt:
            interfaces:
            - name: enp1s0
            method: dhcp
        device: /dev/vda
        iso_url: https://releases.rancher.com/harvester/v0.3.0-rc1/harvester-v0.3.0-rc1-amd64.iso
        vipMode: static
        vip: 192.168.178.40
        poweroff: false
    config_join: &location_X_join
      server_url: https://192.168.178.41:8443
      token: d506621a3d4acdf60d62475f1b2cb681
      os:
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII9lnqlqqlHszXPP8zHFlqrQ4utzVJMSTJI2Qba+zE1s sshkey-X
          - github:your_username
        password: 5up3rS3cr3t 
        dns_nameservers:
          - 192.168.178.3
        ntp_servers:
          - ntp.data.centerx.org
          - ntp.data.centerx.org
      install:
        mode: join
        networks:
          harvester-mgmt:
            interfaces:
            - name: enp1s0
            method: dhcp
        mgmt_interface: enp1s0
        device: /dev/vda
        iso_url: https://releases.rancher.com/harvester/v0.3.0-rc1/harvester-v0.3.0-rc1-amd64.iso
        poweroff: false
  - cluster: location_Y
    config_create: &location_Y_create
      token: 612c99d263fe6b8acb56f0b964e07d0a
      os:
        hostname: harvester01
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII9lnqlqqlHszXPP8zHFlqrQ4utzVJMSTJI2Qba+zE1s sshkey-Y
          - github:your_username
        password: 5up3rS3cr3t
        dns_nameservers:
          - 172.16.128.3
        ntp_servers:
          - ntp.your.org
          - ntp.your.org
      install:
        mode: create
        networks:
          harvester-mgmt:
            interfaces:
            - name: ens3
            method: dhcp
        device: /dev/vda
        iso_url: https://releases.rancher.com/harvester/v0.3.0-rc1/harvester-v0.3.0-rc1-amd64.iso
        vipMode: static
        vip: 172.16.128.40
        poweroff: false
    config_join: &location_Y_join
      server_url: https://172.16.128.41:8443
      token: 612c99d263fe6b8acb56f0b964e07d0a
      os:
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII9lnqlqqlHszXPP8zHFlqrQ4utzVJMSTJI2Qba+zE1s sshkey-Y
          - github:your_username
        password: 5up3rS3cr3t 
        dns_nameservers:
          - 172.16.128.3
        ntp_servers:
          - ntp.your.org
          - ntp.your.org
      install:
        mode: join
        networks:
          harvester-mgmt:
            interfaces:
            - name: ens3
            method: dhcp
        mgmt_interface: enp1s0
        device: /dev/vda
        iso_url: https://releases.rancher.com/harvester/v0.3.0-rc1/harvester-v0.3.0-rc1-amd64.iso
        poweroff: false
maclist:
# harvester v0.2.0
- macaddress: 52:54:00:52:cb:c1
  values:
    ipaddress: 192.168.178.31
    netmask: 255.255.255.0
    gateway: 192.168.178.1
    interface: enp1s0
    version: "v0.2.0"
    type: create
    config: 
      << : *location_X_create
- macaddress: 52:54:00:7d:1a:a2
  values:
    ipaddress: 192.168.178.32
    netmask: 255.255.255.0
    gateway: 192.168.178.1
    interface: enp1s0
    version: "v0.2.0"
    type: join
    config:
      << : *location_X_join
- macaddress: 52:54:00:31:3e:b8
  values:
    ipaddress: 192.168.178.33
    netmask: 255.255.255.0
    gateway: 192.168.178.1
    interface: enp1s0
    version: "v0.2.0"
    type: join
    config:
      << : *location_X_join
# harvester v0.3.0
- macaddress: 52:54:00:c1:6b:56
  values:
    ipaddress: 172.16.128.41
    netmask: 255.255.252.0
    gateway: 172.16.128.254
    interface: ens3
    version: v0.3.0-rc1
    type: create
    config:
      << : *location_Y_create
- macaddress: 52:54:00:14:26:90
  values:
    ipaddress: 172.16.128.42
    netmask: 255.255.252.0
    gateway: 172.16.128.254
    interface: ens3
    version: v0.3.0-rc1
    type: join
    config:
      << : *location_Y_join
- macaddress: 52:54:00:27:8c:78
  values:
    ipaddress: 172.16.128.43
    netmask: 255.255.252.0
    gateway: 172.16.128.254
    interface: ens3
    version: v0.3.0-rc1
    type: join
    config:
      << : *location_Y_join
- macaddress: 52:54:00:9d:cb:2f
  values:
    ipaddress: 172.16.128.44
    netmask: 255.255.252.0
    gateway: 172.16.128.254
    interface: ens3
    version: v0.3.0-rc1
    type: join
    config:
      << : *location_Y_join

